[package]
name = "yagura"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
ratatui = "0.30.0"
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.19.0", features = ["v7"] }
